version: '3'
services:
    postgres:
      image: "postgres"
      environment:
        - POSTGRES_PASSWORD=postgres_password
        - POSTGRES_DB=simple_blog_api
    api:
        depends_on:
            - postgres
        image: parthav030121/simple_blog_api
        build:  .           
        ports:
            - "3000:3000"
        environment:
             - POSTGRES_HOST=postgres
             - POSTGRES_PORT=5432
             - POSTGRES_USERNAME=postgres
             - POSTGRES_PASSWORD=postgres_password
             - POSTGRES_DB=simple_blog_api
