apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
      - name: blog-api
        image: parthav030121/simple_blog_api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000
        env:
            - name: POSTGRES_HOST
              value: postgress-cluster-ip-Service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres   
            - name: POSTGRES_DATABASE
              value: simple_blog_api
            - name: POSTGRES_PASSWORD
              valueFrom:
                   secretKeyRef:                 
                       name: pgpassword
                       key: POSTGRES_PASSWORD     